version: "2.1"

services:
 db:
  image: spgroup_db_img
  container_name: spgroup_db
  build:
   context: ./database
   dockerfile: Dockerfile
  ports:
   - 3306:3306
  environment:
   MYSQL_DATABASE: "spgroup_friendmgmt"
   MYSQL_USER: "friends"
   MYSQL_PASSWORD: "friends"
   MYSQL_ROOT_PASSWORD: "root"
  healthcheck:
    test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW SCHEMAS;\""
    interval: 3s
    timeout: 1s
    retries: 5
 app:
  image: spgroup_app_img
  links:
   - db
  container_name: spgroup_app
  depends_on:
   db:
    condition: service_healthy
  build:
   context: ./application
   dockerfile: Dockerfile
  ports:
   - 8080:8080